### ISSUE TITLE
作者你好，我想问一下应该怎么操作数据？

### ISSUE THREAD

**Issue by Lemon1110** [leeveel/GeekServer#10]
我在现有的背包基础上，新加了一个Gm获得物品的协议，然后调用在BagCompAgent新增的方法 AddItems 对 State.ItemMap 进行数据操作， 但是发现返回的 ReqBagInfo 协议里只有新增的数据？ 难道要像 PlayerInfo 那样 新增一个 state 去管理背包数据吗？那样的话怎么对背包数据进行存储呢？
另外，希望能出一个教程，这样用的人也会多起来！感谢！

**Comment by leeveel** [comment]
可以仔细看看这个十分钟入门教程 https://github.com/leeveel/GeekServer/blob/main/Docs/%E5%8D%81%E5%88%86%E9%92%9F.md
1.对于一个玩家来说，会存在很多功能系统，如角色模块，背包模块，宠物模块，所以按面向对象组件式思维，Role会存在RoleComponent，BagComponent，PetComponent, 而每个系统的数据就存在state当中，即：RoleState,BagState,PetState
2.不需要操作任何数据库，框架底层会自动序列化和反序列话持久化到数据库中，你只需要关心在内存中操作xxxState就行了。

**Comment by Lemon1110** [comment]
感谢解答，但我还是没太明白，，我操作的就是 BagCompAgent 里面的 BagCompAgent 的State.ItemMap啊，但是好像我每次对这个字典进行 Add 操作，就会多出来一个 State， 理论上不应该 一个角色 Actor 的背包 Component 是唯一的吗？
(发送GMAdditem的协议后，收到的背包协议只返回了我新增的那个物品）
[Test.txt](https://github.com/leeveel/GeekServer/files/10097891/Test.txt)

**Comment by leeveel** [comment]
public async Task OnGm(NetChannel channel, GMProto gMProto)
{
    var gmContent = gMProto.GmTxt;
    var param = gMProto.GmParams;
    var role = await GetCompAgent<RoleCompAgent>();
    if (gmContent == "GMAddItem")
    {
        if (!int.TryParse(param[0], out int id))
        {
            LOGGER.Error($"参数1 ItemId 应为 int类型");
            return;
        }
        if (!long.TryParse(param[1], out long count))
        {
            LOGGER.Error($"参数2 Count 应为 long类型");
            return;
        }
        var bag = await role.GetCompAgent<BagCompAgent>();
        bag.AddItems(channel, gMProto.UniId, id, count);
    }
}

1.var role = await GetCompAgent<RoleCompAgent>();这行代码是多余的，应该直接获取 var bag = await GetCompAgent<BagCompAgent>();来直接调用AddItems
2.不过即便是按照你这种写法也应该不会有问题才对，明天我测试下你的代码
3.比如GMComp这种没有state的，可以直接继承BaseComp，不用继承StateComp

**Comment by leeveel** [comment]
1.public class GmHandler : GlobalCompHandler 你的handler继承的是Global
2.[Comp(ActorType.Role)]
public class GMComp : StateComp<GMState> 组件却是注册给Role的。
解决方案：
1.GlobalCompHandler 替换为 RoleCompHandler
2.如果确实要做成全局的，可以注册在ServerActor上[Comp(ActorType.Server)]，如果是采用这种方案，要注意提供给GM调用的接口需要加上[Api]注解（现在已经替换为[Service]）

**Comment by Lemon1110** [comment]
好的好的，非常感谢！问题解决啦
