### ISSUE TITLE
需要详细的文档

### ISSUE THREAD

**Issue by SimpleZDM** [leeveel/GeekServer#11]
作者你好可以加个联系方式吗，我想获取更详细的文档

**Comment by leeveel** [comment]
你好，所有文档都在主页链接了。有什么具体问题都可以在issues提的

**Comment by SimpleZDM** [comment]
看了半天才把流程看明白，希望放一张执行流程的图片
![微信图片_20230228171331](https://user-images.githubusercontent.com/58299933/221807007-9ea1e722-b117-45eb-8da4-d228f50fe507.png)
测试客户端改成控制台版本好像有点问题
![1677575946263](https://user-images.githubusercontent.com/58299933/221808222-6a21fd86-fd53-46a8-82cb-cec349e9001c.png)

**Comment by soulzdm** [comment]
![微信图片_20230228171331](https://user-images.githubusercontent.com/58299933/221806939-1ba60f5d-2f8a-4f22-ad0e-b4a04ddd71c2.png)

**Comment by kane9527-e** [comment]
感谢

**Comment by kane9527-e** [comment]
> 看了半天才把流程看明白，希望放一张执行流程的图片 ![微信图片_20230228171331](https://user-images.githubusercontent.com/58299933/221807007-9ea1e722-b117-45eb-8da4-d228f50fe507.png) 测试客户端改成控制台版本好像有点问题 ![1677575946263](https://user-images.githubusercontent.com/58299933/221808222-6a21fd86-fd53-46a8-82cb-cec349e9001c.png)

感谢
