### ISSUE TITLE
动态模拟

### ISSUE THREAD

**Issue by SimpleZDM** [leeveel/GeekServer#12]
1.大量用户登录，打开测试连接程序吧连接数量设置成一千
2.关闭测试连接程序，此时系统需要释放大量资源
3.这个时候再打开测试程序发现服务器有点处理不过来
不知道是不是可以通过设置Kestrel服务的相关配置解决，希望大佬解答
如果不是希望可以优化
![1677654454215](https://user-images.githubusercontent.com/58299933/222068460-a1d21b04-96c3-4ab0-a94a-836b45ac79c7.png)

**Comment by leeveel** [comment]
好的 我们这边测试下

**Comment by SimpleZDM** [comment]
在实际使用中应该是有用户上线也会有用户下线。上面就是模拟这种情况，数量如果过多就会出现服务异常。是一个动态的过程

**Comment by leeveel** [comment]
你好 我这边重复打开关闭登录测试程序，没发现有释放大量资源导致链接不上的情况呢？

**Comment by SimpleZDM** [comment]
好的，难道是电脑性能的影响。我知道了。代码还是写的非常的精致，非常好，已经阅读了两天了，大部分已经理清楚了。
