### ISSUE TITLE
客户端安卓真机接收消息问题

### ISSUE THREAD

**Issue by L-Fone** [leeveel/GeekServer#15]
请求登录服务器会同时返回两条消息：1.客户端请求返回。2.错误码消息。当在编辑器下，完美收到2条消息返回。但是在安卓真机上，却只能收到一条消息。无法收到错误码消息。导致MsgWaiter无限等待中。

**Comment by L-Fone** [comment]
![QQ截图20230324112810](https://user-images.githubusercontent.com/23207097/227417091-42bacf82-c635-4a94-95c3-c62404cfd132.png)
![QQ截图20230324112855](https://user-images.githubusercontent.com/23207097/227417094-b3fa7770-6ba1-410f-88f6-740ba684b8cb.png)
提供2张图，一张是真机收到的消息输出在控制台，一张是编辑器模式下收到的消息

**Comment by L-Fone** [comment]
![1](https://user-images.githubusercontent.com/23207097/227465248-d47bd2cc-35c6-4ac2-87bb-4af135b7d4fb.png)
![2](https://user-images.githubusercontent.com/23207097/227465213-cd7d861d-d166-4f3f-aa6f-40f2cacb032c.png)
![3](https://user-images.githubusercontent.com/23207097/227465241-b64e4c67-9256-4682-865a-4c0d8a5719c0.png)
![4](https://user-images.githubusercontent.com/23207097/227466185-76a407ee-9731-4e4d-a98a-f9a2a0fcbae6.png)
经查，客户端在安卓真机序列化数据时，父类(Message)中的UniId并没有序列化值，导致传递给服务器时，无法解析到UniId的值，服务器则不返回ResErrorCode。客户端将等待超时。

**Comment by leeveel** [comment]
只会在安卓机上面出现吗？pc上是正确的？

**Comment by L-Fone** [comment]
是的，安卓真机上有必现。目前已经定位到问题所在：因为Geek.MsgPackTool打导出Proto消息时，未对UniId进行写序列化导致的。
把消息文件目录独立出来后，Geek.MsgPackTool无法对Protocol目录下的消息类写出父类中UniId的序列化。
当我尝试在消息文件夹里单独添加一个不带特性的Message基类后，再次导出消息，发现能成功写出对UniId的序列化。
再次打包运行，问题得以解决。
&nbsp;


该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月27日(星期一) 下午4:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leeveel/GeekServer] 客户端安卓真机接收消息问题 (Issue #15)





 
只会在安卓机上面出现吗？pc上是正确的？
