### ISSUE TITLE
配置DBModel模式为1(Mongodb模式)时，数据库无法存储LoginState中的PlayerMap

### ISSUE THREAD

**Issue by L-Fone** [leeveel/GeekServer#16]
用官方示例工程，当服务器配置信息DBModel模式为1时，Mongodb数据库无法存储LoginState中的PlayerMap，导致每次重新启动服务器会创建新玩家。

**Comment by leeveel** [comment]
关闭服务器，是直接关闭的窗口，还是按的ctrl+c ?,后者才会出发钩子函数进行关服强制回存

**Comment by L-Fone** [comment]
无论用ctrl+c，还是Visual Studio调试退出，都能复现这个问题。用示例项目，当模式设置为1时，每次重新运行服务器，将会自动创建新号。数据无法正确得以保存。
&nbsp;


该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月27日(星期一) 下午4:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leeveel/GeekServer] 配置DBModel模式为1(Mongodb模式)时，数据库无法存储LoginState中的PlayerMap (Issue #16)





 
关闭服务器，是直接关闭的窗口，还是按的ctrl+c ?,后者才会出发钩子函数进行关服强制回存

**Comment by leeveel** [comment]
感谢反馈，已修复！
