### ISSUE TITLE
同类游戏服务器太多，建议出一个完整教程

### ISSUE THREAD

**Issue by yilinershi** [leeveel/GeekServer#4]
我看你的更新日志，基本每隔几天就更新维护一下，真算得上是劳模，但也只积累了这些星星。如果用这些时间中的一部分，出个教程，从零开始写个游戏，这项目分分钟升到千星。关注使用的人多了，更利于解决实际问题，更利于这个项目的发展。

个人建议哈！

**Comment by leeveel** [comment]
好的，谢谢建议
