### ISSUE TITLE
Unity2021打开报错

### ISSUE THREAD

**Issue by L-LingRen** [leeveel/GeekServer#7]
Assets\Scripts\Framework\Bedrock\Protocal\ProtocolReader.cs(10,35): error CS0433: The type 'IAsyncDisposable' exists in both 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Assets\Scripts\Framework\Bedrock\Protocal\ProtocolWriter.cs(10,35): error CS0433: The type 'IAsyncDisposable' exists in both 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**Comment by leeveel** [comment]
应该是Unity2021默认支持了netstandard2.1，有些dll自带了，删除提示重复得dll就行了。
给我一个具体版本把，我这边试试

**Comment by L-LingRen** [comment]
2021.3.6f1c1

**Comment by leeveel** [comment]
主干已经修复
