### ISSUE TITLE
如何对接websocket

### ISSUE THREAD

**Issue by a6336747** [leeveel/GeekServer#8]
作者你好,我想用于cocos creator小游戏的服务器框架,想实现一下ws协议,但苦于找不到入口,作者是否能提供一下修改建议,感激不尽

**Comment by leeveel** [comment]
https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/websockets/samples

**Comment by a6336747** [comment]
感谢
